# Generated by Django 5.2.11 on 2026-02-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dry_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('done', 'Completado'), ('na', 'No aplica')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ironing_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('done', 'Completado'), ('na', 'No aplica')], default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='wash_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('done', 'Completado'), ('na', 'No aplica')], default='pending', max_length=20),
        ),
    ]
