# Generated by Django 5.2.11 on 2026-02-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_captured_by_cashsession_cashmovement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashsession',
            name='shift',
            field=models.CharField(choices=[('morning', 'Mañana'), ('evening', 'Tarde')], max_length=20),
        ),
    ]
