# Generated by Django 5.2.11 on 2026-02-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('laundry', 'Lavanderia'), ('ironing', 'Planchado')], default='laundry', max_length=20),
        ),
    ]
