# Generated by Django 5.2.11 on 2026-02-07 16:00

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_service_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="estimated_turnaround_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Tiempo estimado de entrega en horas.",
                validators=[MinValueValidator(1), MaxValueValidator(240)],
            ),
        ),
    ]
