# Generated by Django 5.2.11 on 2026-02-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_estimated_turnaround_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('laundry', 'Lavanderia'), ('wash', 'Lavado'), ('dry', 'Secado'), ('ironing', 'Planchado'), ('special', 'Especial')], default='laundry', max_length=20),
        ),
    ]
